included:
  - Sources
  - Tests

excluded:
  - GeneratedBindings
  - Frameworks

function_body_length:
  warning: 30
  error: 50

type_body_length:
  warning: 250
  error: 350

file_length:
  warning: 350
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 15
